name: "Terraform-IAC-AKS"
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - stage
#     paths:  
#       - terraform/**
#   pull_request:
#     branches:
#       - main
#     paths:
#       - terraform/**

jobs:
   terraform:
     name: "Apply terraform code changes"
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
         working-directory: ./Terraform

     steps:

        - name: Checkout source code
          uses: actions/checkout@v4

        - name: Log in with Azure
          uses: azure/login@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'

        - name: Message after Login
          run: echo Hello, world! Logged in to Azure

        - name: Setup Terraform with specified version on the runner
          uses: hashicorp/setup-terraform@v2

        - name: Terraform init
          id: init
          run: terraform init

        - name: Terraform format
          id: fmt
          run: terraform fmt -check

        - name: Terraform validate
          id: validate
          run: terraform validate

        - name: Terraform plan
          id: terra_plan
          run: terraform plan -no-color -input=false -out planfile
          continue-on-error: true

        - name: Terraform plan status
          if: steps.terra_plan.outcome == 'failure' 
          run: exit 1

        - name: Terraform Apply
          id: terra_apply
          #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          run: terraform apply -auto-approve -input=false -parallelism=1 planfile